In [1]:
# Bibliothèques pour la viz
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot') or plt.style.use('ggplot')

import plotly.express as px

import seaborn as sns
sns.set_style('darkgrid')

import warnings
warnings.filterwarnings('ignore')

# Bibliothèques pour la manipulation de données
import pandas as pd
import numpy as np


In [2]:


# Lire le fichier CSV
data = pd.read_csv(r"C:\Users\DELL 7480\Documents\PROTOJAM\speed_data_data.csv", sep =',')

In [3]:
# Supprimer les lignes contenant des valeurs manquantes
data_cleaned = data.dropna()

In [ ]:
data_cleaned.describe().T

In [4]:
#CREATION COLONNE ID


# Créer un dictionnaire pour stocker les index correspondant à chaque valeur de "income"
index_dict = {}

# Parcourir le DataFrame et assigner un index unique pour chaque valeur de "income"
for index, row in data_cleaned.iterrows():
    income = row['income']
    if income not in index_dict:
        index_dict[income] = len(index_dict)  # Utilisation de len(index_dict) pour obtenir un index unique
    data_cleaned.at[index, 'ID'] = int(index_dict[income])  # Convertir en entier

# Convertir la colonne "ID" en type entier
data_cleaned['ID'] = data_cleaned['ID'].astype(int)

In [ ]:
# pip install ydata-profiling

from pandas_profiling import ProfileReport

profile_data_cleaned = ProfileReport(data_cleaned, title='Profiling Report')

profile_data_cleaned

In [ ]:
# pip install dtale

import dtale

dtale.show(data_cleaned)

In [5]:
groupes_metiers = {
    'finance': ['Financial Services', 'Capital Markets', 'Investment Banking', 'Microfinancing Program Manager', 'Asset Management', 'Real Estate', 'Finance', 'Investment Management', 'Real Estate/ Private Equity', 'corporate finance', 'Trader', 'Venture Capital/Consulting/Government', 'Investment banking', 'Finance Related', 'Fixed Income Sales & Trading', 'M&A Advisory', 'Banking', 'Energy Management', 'Business Management', 'Microfinancing Program Manager'],
    'health': ['health/nutrition oriented social worker', 'Cardiologist', 'Pediatrics', 'medicine', 'Neuroscientist/Professor', 'Psychologist', 'clinical psychologist', 'Clinical Social Worker', 'Physician', 'Epidemiologist', 'Nutritionist', 'clinical psychologist', 'physician/healthcare', 'Sex Therapist', 'Doctor'],
    'justice': ['lawyer', 'law', 'lawyer/policy work', 'Law', 'Corporate Lawyer', 'Corporate attorney', 'Speech Language Pathologist', 'Intellectual Property Attorney', 'Academic Physician', 'attorney', 'Law or finance', 'Legal', 'Assistant District Attorney'],
    'social_worker': ['Social Worker', 'Social work with children', 'Social Work Administration', 'Social Services/ Policy', 'Social Work', 'School Psychologist', 'School Counseling', 'Social Work Policy', 'Exec. Director of social service non-profit'],
    'professor': ['academics or journalism','clinical psychologist, researcher, professor', 'Professor of Media Studies', 'Teacher/Professor', 'Professor', 'Teacher/Professor', 'professor', 'academics', 'academic research', 'academic', 'academia', 'college professor', 'college art teacher', 'History Professor', 'English Teacher', 'College Professor', 'High School Social Studies Teacher', 'Elementary Education Teaching', 'Elementary school teacher', 'Bilingual Elementary School Teacher', 'Professor; Human Rights Director', 'English teacher', 'teacher and performer'],
    'others': ['Informatics', "Clidren's TV", 'Organizational Change Consultant', 'tech professional', 'Engineer', 'Entrepreneur', 'consulting', 'novelist', 'Pro Beach Volleyball', 'teaching and then...', 'Marketing, Advertising', 'brand management', 'president', 'nutrition and dental', 'Art educator and Artist', 'Scientist', 'Who knows', 'Media Marketing/Entrepreneurship', 'Filmmaker', 'writer/editor', 'producer at a non-profit regional theatre', "Diplomat / Int'l civil servant", 'unsure', 'Actress', 'Writer/journalist', 'Foreign Service', 'General Management', 'Energy', 'Management Consulting', 'Trade Specialist', 'Economic Policy Advisor on Latin America', 'Media Management', 'writer', 'consultant', 'researcher', 'film and radio', 'Film', 'researcher', 'unsure']
}







In [6]:
def cat_career(job,dict_jobs=groupes_metiers):
    for k,v in dict_jobs.items():
        if job in v:
            return k

In [7]:
data_cleaned['carrer_cat']=data_cleaned['career'].map(cat_career)

In [10]:
data_cleaned

gender   age   income  goal   career  dec  attr  sinc  intel  fun  amb  \
0          0  21.0  69487.0   2.0   lawyer    1   6.0   9.0    7.0  7.0  6.0   
1          0  21.0  69487.0   2.0   lawyer    1   7.0   8.0    7.0  8.0  5.0   
3          0  21.0  69487.0   2.0   lawyer    1   7.0   6.0    8.0  7.0  6.0   
4          0  21.0  69487.0   2.0   lawyer    1   5.0   6.0    7.0  7.0  6.0   
5          0  21.0  69487.0   2.0   lawyer    0   4.0   9.0    7.0  4.0  6.0   
...      ...   ...      ...   ...      ...  ...   ...   ...    ...  ...  ...   
8351       1  27.0  55138.0   1.0  Banking    0   7.0   7.0    7.0  7.0  7.0   
8352       1  27.0  55138.0   1.0  Banking    0   6.0   6.0    6.0  6.0  6.0   
8353       1  27.0  55138.0   1.0  Banking    0   7.0   7.0    7.0  7.0  7.0   
8354       1  27.0  55138.0   1.0  Banking    0   5.0  10.0   10.0  8.0  6.0   
8355       1  27.0  55138.0   1.0  Banking    0   4.0   9.0    9.0  7.0  7.0   

      shar  like  prob  met   ID carrer_cat  
0      5.0   7.0   6.0  2.0    0    justice  
1      6.0   7.0   5.0  1.0    0    justice  
3      8.0   7.0   6.0  2.0    0    justice  
4      6.0   6.0   6.0  2.0    0    justice  
5      4.0   6.0   5.0  2.0    0    justice  
...    ...   ...   ...  ...  ...        ...  
8351   7.0   8.0   1.0  1.0  254    finance  
8352   6.0   6.0   1.0  1.0  254    finance  
8353   7.0   9.0   1.0  1.0  254    finance  
8354   5.0   8.0   5.0  0.0  254    finance  
8355   6.0   7.0   5.0  0.0  254    finance  

[3501 rows x 17 columns]

In [26]:
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [24]:


clean_speed = data_cleaned.groupby(['ID', 'gender','income','carrer_cat','age'])[['amb', 'attr', 'fun']].mean().reset_index().round(2)
clean_speed.head(5)

#books['reviews_opinion'] = books['average_rating'].apply(reviews_opinion)



ID  gender   income carrer_cat   age   amb  attr   fun
0   0       0  69487.0    justice  21.0  6.62   6.0  6.75
1   1       0  65929.0    justice  24.0  6.50   6.4  6.10
2   2       0  37754.0    justice  23.0  7.80   6.4  7.80
3   3       0  86340.0    justice  21.0  5.60   6.3  6.00
4   4       0  60304.0    justice  23.0  5.20   5.9  6.00

In [32]:
clean_speed.to_csv('clean_speed.csv')

In [ ]:
data_cleaned.columns = ['unique_career']

data_cleaned.head(30)

In [14]:
#clean_speed.rename(columns={'amb':'amb_moy', 'attr': 'attr_moy', 'fun': 'fun_moy'})
speed_datingdf = pd.merge(clean_speed, data_cleaned, on= 'income')

speed_datingdf.head(15)

income     amb_x    attr_x     fun_x  gender   age  goal          career  \
0    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
1    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
2    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
3    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
4    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
5    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
6    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
7    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
8    8607.0  7.555556  5.888889  7.222222       0  29.0   2.0       president   
9   12063.0  8.000000  6.000000  7.500000       1  27.0   6.0          lawyer   
10  12063.0  8.000000  6.000000  7.500000       1  27.0   6.0          lawyer   
11  12416.0  7.800000  6.200000  7.000000       1  24.0   5.0  Epidemiologist   
12  12416.0  7.800000  6.200000  7.000000       1  24.0   5.0  Epidemiologist   
13  12416.0  7.800000  6.200000  7.000000       1  24.0   5.0  Epidemiologist   
14  12416.0  7.800000  6.200000  7.000000       1  24.0   5.0  Epidemiologist   

    dec  attr_y  sinc  intel  fun_y  amb_y  shar  like  prob  met   ID  \
0     1     5.0   6.0    8.0    7.0    6.0   6.0   7.0   7.0  0.0  129   
1     0     5.0   7.0    8.0    6.0    7.0   5.0   6.0   6.0  0.0  129   
2     0     4.0   7.0   10.0    7.0    8.0   5.0   6.0   4.0  0.0  129   
3     0     4.0   9.0    8.0    6.0    6.0   4.0   6.0   5.0  0.0  129   
4     0     5.0  10.0   10.0    9.0    6.0   7.0   8.0   6.0  0.0  129   
5     1    10.0   6.0    8.0    9.0    7.0   5.0   7.0   6.0  0.0  129   
6     0     5.0   8.0    9.0    6.0   10.0   5.0   6.0   6.0  0.0  129   
7     1     8.0   6.0   10.0    9.0   10.0   9.0   8.0   7.0  0.0  129   
8     0     7.0   7.0    9.0    6.0    8.0   5.0   6.0   4.0  0.0  129   
9     0     6.0   8.0    8.0    7.0    8.0   5.0   7.0   7.0  2.0   27   
10    0     6.0   8.0    8.0    8.0    8.0   5.0   7.0   7.0  2.0   27   
11    0     4.0   7.0    9.0    5.0    8.0   5.0   6.0   5.0  0.0  234   
12    1     7.0   8.0    9.0    6.0    8.0   5.0   7.0   5.0  0.0  234   
13    0     6.0   9.0    9.0    8.0    5.0   6.0   8.0   5.0  0.0  234   
14    1     7.0   9.0    9.0    7.0    9.0   7.0   8.0   5.0  0.0  234   

   carrer_cat  
0      others  
1      others  
2      others  
3      others  
4      others  
5      others  
6      others  
7      others  
8      others  
9     justice  
10    justice  
11     health  
12     health  
13     health  
14     health

In [27]:
from sklearn.neighbors import NearestNeighbors

In [28]:
df_speedML = clean_speed[['gender', 'age','attr','fun', 'amb' ]]
speedvoisin = NearestNeighbors(n_neighbors=3)

speedvoisin.fit(df_speedML)

NearestNeighbors(n_neighbors=3)

In [29]:
distances, indices = speedvoisin.kneighbors(df_speedML)
print(indices)

[[  0  36 151]
 [  1  17  85]
 [  2  55  57]
 [  3  29   0]
 [  4  23  90]
 [  5  22 151]
 [  6  51 156]
 [  7 121  55]
 [  8  97 111]
 [  9  81  54]
 [ 10 159 116]
 [ 11 100  89]
 [ 12 147 100]
 [ 13 109  66]
 [ 14 144  90]
 [ 15  14  28]
 [ 16  39   6]
 [ 17  23  85]
 [ 18  38 126]
 [ 19 152  57]
 [ 20  32 149]
 [ 21 101 108]
 [ 22 122   5]
 [ 23  17  85]
 [ 24  43 152]
 [ 25 136 146]
 [ 26 102  93]
 [ 27 117 125]
 [ 28  63  90]
 [ 29   6   3]
 [ 30 114   9]
 [ 31 105  88]
 [ 32  94  20]
 [ 33  79  82]
 [ 34  45  52]
 [ 35  68  69]
 [ 36  67 151]
 [ 37  19  88]
 [ 38  18 133]
 [ 39  16  36]
 [ 40 136  25]
 [ 41  60  81]
 [ 42 103 114]
 [ 43  26 102]
 [ 44  45  46]
 [ 45  49  46]
 [ 46  45  96]
 [ 47   3  29]
 [ 48   6  83]
 [ 49  45  34]
 [ 50 134  99]
 [ 51 156   6]
 [ 52  36  67]
 [ 53  60 119]
 [ 54  75 117]
 [ 55  91   2]
 [ 56  31 105]
 [ 57  91   2]
 [ 58  91  57]
 [ 59  65 149]
 [ 60  41  30]
 [ 61  43  26]
 [ 62  78  61]
 [ 63  28  90]
 [ 64  37 150]
 [ 65  59  18]
 [ 66  92 

In [35]:
import pickle

In [36]:
with open('model.pkl', 'wb') as f:
    pickle.dump(speedvoisin, f)

In [30]:
test = df_speedML.iloc[0].values.reshape(1, -1)
distances, indices = speedvoisin.kneighbors(test)

print("Indices des voisins les plus proches :", indices)
print("Distances des voisins les plus proches :", distances)


Indices des voisins les plus proches : [[  0  36 151]]
Distances des voisins les plus proches : [[0.         1.23454445 1.2541531 ]]


In [ ]:
data_cleaned['neighbors_income'] = [[] for _ in range(len(data_cleaned))]
data_cleaned['neighbors_cat_carrer'] = [[] for _ in range(len(data_cleaned))]

for i, neighbor_indices in enumerate(indices):
    data_cleaned.at[i, 'neighbors_income'] = data_cleaned.iloc[neighbor_indices]['income'].tolist()
    data_cleaned.at[i, 'neighbors_cat_carrer'] = data_cleaned.iloc[neighbor_indices]['cat_carrer'].tolist()

print(data_cleaned)

In [4]:
from faker import Faker
import pandas as pd

fake = Faker('fr_FR')

data_fake = {
    'name': [fake.name() for _ in range(30)],
    'address': [fake.address() for _ in range(30)],
    'email': [fake.email() for _ in range(30)]
    }

df_fake = pd.DataFrame(data_fake)
df_fake.to_csv('data_fake.csv')